esphome:
  name: 70-esphome
  friendly_name: 7.0_ESPHOME
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.esp-idf.memory_type: qio_opi
    board_build.flash_mode: dio
    #board_upload.maximum_ram_size: 524288

esp32:
  board: esp32-s3-devkitc1-n4r8
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHFREQ: "80MHz" # this is needed for flashing
      CONFIG_ESPTOOLPY_FLASHMODE_QIO: y
      CONFIG_FLASHMODE_QIO: y
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240: y
      CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ: '240'
      CONFIG_SPIRAM_RODATA: "y"

# Enable PSRAM on ESP32-S3
psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "R81dZPB43jGUEEMAwYgg9fYnQ6YBa00kglPr1AoYh7M="

ota:
  - platform: esphome
    password: "146aa53cb51257821e9cbeb0015791d5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "70-Esphome Fallback Hotspot"
    password: "5ZQEYLMljDBr"

captive_portal:


# I2C bus configuration
i2c:
  - id: i2c_bus
    sda: GPIO19
    scl: GPIO20
    scan: true

# PCA9554 GPIO extender for display reset
pca9554:
  - id: p_c_a
    address: 0x20
    i2c_id: i2c_bus

switch:
  - platform: gpio
    pin: 38
    id: output_pin
    name: "Pin 38 Output"

  - platform: gpio
    name: "GT911 Reset"
    pin:
      pca9554: p_c_a
      number: 0
      mode:
        output: true
      inverted: false
    id: gt911_reset

  - platform: gpio
    name: "GT911 INT"
    pin:
      pca9554: p_c_a
      number: 1
      mode:
        output: true
      inverted: false
    id: gt911_int

script:
  - id: init_touch
    mode: queued
    then:
      - switch.turn_off: gt911_reset
      - switch.turn_off: gt911_int
      - delay: 20ms
      - switch.turn_on: gt911_reset
      - delay: 100ms
      - switch.turn_off: gt911_int

output:
  - platform: ledc
    pin: 2
    frequency: 1220
    id: gpio_backlight_pwm

light:
  - platform: monochromatic
    output: gpio_backlight_pwm
    id: display_backlight
    restore_mode: ALWAYS_ON
    name: ${devicename} Display Backlight
    
#设置屏幕配置
display:
  - platform: rpi_dpi_rgb
    id: my_display
    color_order: RGB
    invert_colors: True
    update_interval: 16ms
    auto_clear_enabled: false # takes 2.8 seconds to clear the display
    dimensions:
      width: 800
      height: 480
    de_pin: 41
    hsync_pin: 39
    vsync_pin: 40
    pclk_pin: 0
    pclk_frequency: 20MHz
    hsync_pulse_width: 48
    hsync_front_porch: 40
    hsync_back_porch: 40
    vsync_pulse_width: 31
    vsync_front_porch: 1
    vsync_back_porch: 13
    data_pins:
      red:
        - 14        #r1
        - 21        #r2
        - 47        #r3
        - 48        #r4
        - 45        #r5
      green:
        - 9         #g0
        - 46         #g1
        - 3         #g2
        - 8        #g3
        - 16        #g4
        - 1         #g5
      blue:
        - 15         #b1
        - 7         #b2
        - 6        #b3
        - 5         #b4
        - 4         #b5



touchscreen:
  - platform: gt911
    id: my_touchscreen
    i2c_id: i2c_bus
    on_update:
        - lvgl.label.update:
            id: coord_text
            text: !lambda return str_sprintf("Touch points:\n id=%d x=%d, y=%d", touches[0].id, touches[0].x, touches[0].y);
        - lambda: |-
            for (auto touch: touches)  {
                if (touch.state <= 2) {
                  ESP_LOGI("Touch points:", "id=%d x=%d, y=%d", touch.id, touch.x, touch.y);
                }
            }
    on_release:
      - if:
          condition: lvgl.is_paused
          then:
            - logger.log: "LVGL resuming"
            - lvgl.resume:
            - lvgl.widget.redraw:
            - light.turn_on: 
                id: display_backlight
                brightness: 50%

image:
  - file: "small_logo.png"
    id: small_logo
    resize: 250x52
    type: RGB565

# LVGL Configuration
lvgl:
  - id: lvgl_display
    displays:
      - my_display
    widgets:
      - image:
          src: small_logo
          id: lvgl_logo
          zoom: 2
          x: 300
          y: 40
      - label:
          id: coord_text
          align: CENTER
          text_align: CENTER
          text: 'Touch the screen'
